mysite/urls.py
from django.conf.urls import patterns, include, url

from django.conf.urls.static import static
from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin

# from youtubetomp3 import views

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mysite.views.home', name='home'),
    # url(r'^mysite/', include('mysite.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    
    url(r'^', include('youtubetomp3.urls', namespace="youtubetomp3")),

    # url(r'^accounts/profile/$', views.profile, name="profile_detail"),
    url(r'^accounts/', include('registration.backends.default.urls')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

youtubetomp3/urls.py
from django.conf.urls import patterns, url

from youtubetomp3 import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^contacts/$', views.contacts, name='contacts'),
    url(r'^support/$', views.support, name='support'),
    url(r'^about/$', views.about, name='about'),
    url(r'^download/$', views.download, name="download"),
    url(r'^convert/(?P<stream>[\w|\W]+)/$', views.convert, name="convert"),
    url(r'^poll_state/$', views.poll_state, name="poll_state"),
    url(r'^playlists/$', views.playlists, name="playlists"),
    url(r'^new-playlist/$', views.new_playlist, name="new_playlist"),

    url(r'^playlists/remove/playlist=(?P<playlistName>[\w|\W]+),is_audio=(?P<is_audio>[\w|\W]+)/$', 
        views.remove_playlist, name="remove_playlist"),

    url(r'^playlists/(?P<playlistName>[\w|\W]+)/remove=(?P<media>[\w|\W]+)/$', 
        views.remove_media, name="remove_media"),
    url(r'^playlists/(?P<playlistName>[\w|\W]+)/update/name=(?P<name>[\w|\W]+);color=(?P<color>[\w|\W]+)/$', 
        views.change_playlist, name="change_playlist"),
    url(r'^playlists/(?P<playlistName>[\w|\W]+)/update/mediaId=(?P<mediaId>[\w|\W]+)/$', 
        views.change_media, name="change_media"),
    url(r'^playlists/(?P<playlistName>[\w|\W]+)/audio=(?P<media>[\w|\W]+);type=(?P<mediatype>[\w|\W]+)/$', 
        views.audio, name="audio"),
    url(r'^playlists/(?P<playlist_name>[\w|\W]+)/add/media=(?P<media>[\w|\W]+)/$', 
        views.add_media_to_playlist, name="add_media_to_playlist"),
    url(r'^playlists/(?P<playlistName>[\w|\W]+)/$', views.playlist, name="playlist"),
    
    # url(r'^accounts/profile/$', views.profile, name="profile_detail"),
    # url(r'^accounts/', include('registration.backends.default.urls')),
    # url(r'^profiles/', include('profiles.urls')),
    # url(r'^accounts/login/$', 'django.contrib.auth.views.login', {'login': 'youtubetomp3/login.html'}),
)

youtubetomp3/models.py
from django.db import models
from django.contrib.auth.models import User
import os

from youtubetomp3.const.constants import _Const
import youtubetomp3.core.utils as Utils

CONST = _Const()

class PlaylistManager(models.Manager):
    """PlaylistManager with checking on name"""
    def create_playlist(self, name, user, is_audio):
        if self.filter(name=name, user=user, is_audio=is_audio).count() != 0:
            return CONST.DUBLICATE
        else:
            return self.create(user=user, name=name, is_audio=is_audio)

class Playlist(models.Model):
    """Playlist which contains media objects"""

    class Meta:
        ordering = ['name']

    user = models.ForeignKey(User)
    name = models.CharField(max_length=50)
    is_audio = models.BooleanField(default=True)
    color = models.CharField(max_length=15, default='fff')
    objects = PlaylistManager()

    def __unicode__(self):
        return self.user.username + ": " + self.name

    def get_default_playlist(self):
        """ Returns default playlist (video or audio) according to is_audio field """
        if self.is_audio:
            playlist_name = CONST.DEFAULT_AUDIO_PLAYLIST
        else:
            playlist_name = CONST.DEFAULT_VIDEO_PLAYLIST

        return Playlist.objects.get(
            user=self.user, name=playlist_name, is_audio=self.is_audio)

class MediaManager(models.Manager):
    """MediaManager with checking on name"""
    def create_media(self, playlist, name, link_to_play, link_to_load):

        if self.filter(playlist=playlist, 
            name=name,
            link_to_play=link_to_play, 
            link_to_load=link_to_load).count() != 0:
        
            return CONST.DUBLICATE
        else:
            return self.create(playlist=playlist, 
                name=name, 
                link_to_play=link_to_play, 
                link_to_load=link_to_load)    
        
class Media(models.Model):
    """Media files in playlist. Contains link on media file"""

    class Meta:
        ordering = ['name']

    playlist = models.ForeignKey(Playlist)
    name = models.CharField(max_length=50)
    link_to_play = models.CharField(max_length=50)
    link_to_load = models.CharField(max_length=50)
    objects = MediaManager()

    def __unicode__(self):
        return self.playlist.user.username + ": " + self.link_to_play

    def rename(self, newName):
        self.name = newName

        self.link_to_play = Utils.rename(
            os.path.basename(self.link_to_play), newName, self.playlist.user)
        self.link_to_load = Utils.rename(
            os.path.basename(self.link_to_load), newName, self.playlist.user)

        self.save()

    def delete(self):

        if (self.playlist.name == CONST.DEFAULT_AUDIO_PLAYLIST 
            or self.playlist.name == CONST.DEFAULT_VIDEO_PLAYLIST):

            os.remove(Utils.createPath(
                os.path.basename(self.link_to_play), 
                self.playlist.user))

            if self.link_to_play != self.link_to_load:
                os.remove(Utils.createPath(
                    os.path.basename(self.link_to_load), 
                    self.playlist.user))
        
        super(Media, self).delete()


        
        

youtubetomp3/views.py
# Create your views here.

from celery.result import AsyncResult

from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.template import RequestContext, loader
from django.utils import simplejson as json
from django.utils.encoding import smart_str

import os

from youtubetomp3.core.jobs import convert as converter
from youtubetomp3.core.jobs import download as downloader

from youtubetomp3.models import Playlist
from youtubetomp3.models import Media

from youtubetomp3.const.constants import _Const
CONST = _Const()

import youtubetomp3.core.utils as Utils


def index(request):
    return render(request, 'youtubetomp3/index.html')

def contacts(request):
    return render(request, 'youtubetomp3/footer/contacts.html')

def support(request):
    return render(request, 'youtubetomp3/footer/support.html')

def about(request):
    return render(request, 'youtubetomp3/footer/about.html')

def poll_state(request):
    """ A view to report the progress to the user """
    if 'job' in request.GET:
        job_id = request.GET['job']
    else:
        return HttpResponse('No job id given.')

    job = AsyncResult(job_id)
    data = job.result or job.state

    return HttpResponse(json.dumps(data), mimetype='application/json')

def download(request):
    """ A view to start a background job """
    job = downloader.delay(request.POST['youtubeLink'], request.user)    
    return HttpResponse(job)

def convert(request, stream):
    """ A view to start a background job """
    if stream == 'audio':
        job = converter.delay(request.POST['medialink'], request.user)
    else:
        job = converter.delay(request.POST['medialink'], request.user, 
            CONST.VIDEO_TO_LOAD_EXTENSION)
        
    return HttpResponse(job)

def playlists(request):
    """ Users playlists """
    template = loader.get_template('youtubetomp3/playlists.html')
    context = RequestContext(request)

    return HttpResponse(template.render(context))

def profile(request):
    """ A profile view """
    template = loader.get_template('profiles/profile_detail.html')
    context = RequestContext(request)

    return HttpResponse(template.render(context))

def playlist(request, playlistName):
    """ Media playlist """
    user = request.user
    playlist = user.playlist_set.get(name=playlistName, user=user)
    media_set = playlist.media_set.all()

    template = loader.get_template('youtubetomp3/playlist.html')
    context = RequestContext(request, {'playlist' : playlist, 'media_set' : media_set})

    return HttpResponse(template.render(context))

def audio(request, playlistName, media, mediatype):
    
    response = HttpResponse(mimetype=mediatype)
    response['Content-Disposition'] = 'attachment; filename=%s' % smart_str(media)
    response['Accept-Ranges'] = 'bytes'
    path = Utils.createPath(os.path.basename(media), request.user)
    response['X-Sendfile'] = smart_str(path)

    return response

def new_playlist(request):
    """ Create new playlist """
    user = request.user

    if 'playlist' in request.POST:
        playlistName = request.POST['playlist']

        if 'is_audio' in request.POST:
            is_audio = True
        else:
            is_audio = False

    if playlistName != None:
        playlist = Playlist.objects.create_playlist(name=playlistName, user=user, is_audio=is_audio)

    if (playlist != CONST.DUBLICATE):
        print 'created new playlist with name ' + playlist.name

    return HttpResponseRedirect(reverse('youtubetomp3:playlists'))

def remove_playlist(request, playlistName, is_audio):
    """ Remove playlist """

    user = request.user

    # Fucking sheet! In some way if is_audio==False, it is string 'False' instead of bool
    if is_audio == 'False':
        is_audio = False

    playlist = Playlist.objects.get(
        name=playlistName, user=user, is_audio=is_audio)

    for media in playlist.media_set.all():
        media.delete()

    playlist.delete()

    return HttpResponseRedirect(reverse('youtubetomp3:playlists'))

def remove_media(request, playlistName, media):
    """ Remove media """
    
    user = request.user
    playlist = user.playlist_set.get(name=playlistName, user=user)
    playlist.media_set.get(link_to_play=media).delete()

    return HttpResponseRedirect(
        reverse('youtubetomp3:playlist', args=[playlistName,]))

def change_playlist(request, playlistName, name=None, color=None):
    
    user = request.user
    redirect = False
    playlist = user.playlist_set.get(name=playlistName, user=user)

    if name == None:
        name = playlist.name
    elif color == None:
        color = playlist.color
    elif 'playlist' in request.POST:
        redirect = True
        name = request.POST['playlist']

    if playlistName != CONST.DEFAULT_VIDEO_PLAYLIST and playlistName != CONST.DEFAULT_AUDIO_PLAYLIST: 
        playlist.name = name
    else:
        name = playlistName
        
    playlist.color = color
    playlist.save()

    pair = {'name': name, 'color': color}

    if redirect:
        return HttpResponseRedirect(
            reverse('youtubetomp3:playlist', args=[name,]))
    else:
        return HttpResponse(json.dumps(pair), mimetype='application/json')

def change_media(request, playlistName, mediaId):

    if 'playlist' in request.POST:
        medianame = request.POST['playlist']

    media = Media.objects.get(id=mediaId)

    for med in Media.objects.filter(link_to_play=media.link_to_play): 
        med.rename(medianame)
        media = med

    pair = { 'id': mediaId, 'name': medianame, 
             'link_to_play': media.link_to_play, 
             'link_to_load': media.link_to_load }

    return HttpResponse(json.dumps(pair), mimetype='application/json')

def add_media_to_playlist(request, playlist_name, media):
    """ Adds media to given playlist """
    user = request.user
    playlist_to_add = user.playlist_set.get(name=playlist_name, user=user)
    media_field = Media.objects.filter(link_to_play=media)[0]

    Media.objects.create_media(playlist=playlist_to_add, 
        name=media_field.name,
        link_to_play=media_field.link_to_play, 
        link_to_load=media_field.link_to_load)

    return HttpResponseRedirect(
        reverse('youtubetomp3:playlist', args=[playlist_name,]))


youtubetomp3/templates/youtubetomp3/audio.html
<!-- Includes the necessary CSS and Javascript libraries for full customization -->
{% load staticfiles %}
<tr id="{{ media.id }}">

    <audio id="song{{ media.id }}" ontimeupdate="updateTime()" preload="metadata">
        <source src="{{ media.link_to_load }}" type="audio/mpeg"/>
        <source src="{{ media.link_to_play }}" type="audio/ogg"/>
        Your browser does not support the audio tag.
    </audio>

    <!--<input type="hidden" id="songSrc{{ media.id }}" value="{{ media.mediafile }}">-->

    <td style="width: 10%;">
        <div class="audioitem">
            <div class="btn btn-danger" type="button" id="songPlayPause" onclick="playPause('{{ media.id }}')">
                <img id="play-pause" src="{% static 'img/play.png' %}">
                <input type="hidden" id="songPlayImage" value="{% static 'img/play.png' %}">
                <input type="hidden" id="songPauseImage" value="{% static 'img/pause.png' %}">
            </div>
        </div>
    </td>

    <!-- Song Slider tracks progress on song time change, if you click it sets the distance into the song
    based on the percentage of where was clicked -->
    <td style="width: 75%;">
        <div class="audioitem">
            <p id="name{{ media.id }}" class="in-one-line audioname">{{ media.name }}</p>
            <a
                title="Rename audio"
                data-toggle="modal"
                class="in-one-line"
                href="#changeNameModal"
                onclick="changeMediaName('{% url 'youtubetomp3:change_media' playlist.name media.id %}')">

                    <img class="edit-button" src="{% static 'img/edit.png' %}">

            </a>
            <div id="songTime" class="in-one-line audioname time" style="float: right;">0:00</div>
            <div id="songSlider" onclick="setSongPosition(this,event)"><div id="trackProgress"></div></div>
        </div>
    </td>
    <!-- Volume Meter sets the new volume on click.  The Volume Status div is embedded inside so it can grow
    within bounds to simulate percentage feel -->
    <td style="width: 15%;">
        <div class="audioitem">
            <div id="volumeMeter" onclick="setNewVolume(this,event,{{ media.id }})"><div id="volumeStatus"></div></div>
        </div>
    </td>

    <td style="width: 5%;">
        <div class="audioitem">
            <a title="Download" href="{{ media.link_to_load }}"><img src="{% static 'img/download.png' %}"></a>
        </div>
    </td>

    <td style="width: 5%;">
        <div class="audioitem">
            <a title="Delete" type="button" class="close" data-dismiss="modal" aria-hidden="true" href="{% url 'youtubetomp3:remove_media' playlistName=playlist.name media=media.link_to_play %}" method="GET">
                &times;
            </a>
        </div>
    </td>

</tr>

youtubetomp3/templates/youtubetomp3/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="GetYouMusic">
    <meta name="author" content="Sergey Moysa">
    <link rel="shortcut icon" href="{% static 'ico/favicon.png' %}">

    <title>{% block title %}Tutu{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" media="screen">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/base.css' %}" rel="stylesheet">
    {% block style %}{% endblock %}

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="../../assets/js/html5shiv.js"></script>
      <script src="../../assets/js/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <!-- wrap for sticky footer -->
    <div id="wrap"> 
      

      <div class="container">

        <!-- navigation bar -->
        <div class="navbar-wrapper">
          <div class="container">

            <div class="navbar navbar-inverse"> 
              <div class="container">
                <div class="navbar-header">
                  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                  </button>
                  <a class="navbar-brand" href="{% url 'youtubetomp3:index' %}"><img src="{% static 'img/logo.png' %}" id="logo"></a>
                </div>
                <div class="navbar-collapse collapse">
                  {% block sidebar %}
                  <ul class="nav navbar-nav">
                    <li class="active"><a href="{% url 'youtubetomp3:index' %}">Home</a></li>
                    <li><a href="{% url 'youtubetomp3:playlists' %}">Playlists</a></li>
                  </ul>
                  {% endblock %}
                  <ul class="nav navbar-nav navbar-right">

                    {% if user.is_active %}

                      <p class="navbar-text pull-right">Signed as <b>
                                  {{ user.username }}
                                
                              </b>. <a href="{% url 'auth_logout' %}" class="navbar-link">Logout</a>
                      </p>
                    
                    {% else %}

                      <li><a href="{% url 'auth_login' %}">Log in</a></li>
                      <li><a href="{% url 'registration_register' %}">Sign up</a></li>

                    {% endif %}
                  </ul>
                </div><!--/.nav-collapse -->
              </div>
            </div>
          </div>
        </div>

        <!-- Put body content here -->
        <!--_______________________-->
        <div class="stuff">
          {% block content %}{% endblock %}
        </div>

      </div><!-- end of container -->

      <!-- For using without margins (10% 10%) -->
      {% block afterContainer %}{% endblock %}

    </div><!-- end of wrap -->

    <!-- Footer -->
    <div id="footer">
      <div class="container">
        <div class="row">
            <div class="col-xs-14 col-sm-9 col-lg-9">
                <p class="text-muted credit">Copyright by ...</p> 
            </div>
            <div class="col-xs-2 col-sm-1 col-lg-1">
                <a href="{% url 'youtubetomp3:contacts' %}" class="text-muted credit"><p>Contacts</p></a>
            </div>
            <div class="col-xs-2 col-sm-1 col-lg-1">
                <a href="{% url 'youtubetomp3:support' %}" class="text-muted credit"><p>Support</p></a>
            </div>
            <div class="col-xs-2 col-sm-1 col-lg-1">
                <a class="text-muted credit" href="{% url 'youtubetomp3:about' %}"><p>About us</p></a>
            </div>
        </div>
      </div>
    </div> <!-- Footer end -->

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    {% block javascript %}{% endblock %}
    
  </body>
</html>

youtubetomp3/templates/youtubetomp3/playlist.html
{% extends "youtubetomp3/base.html" %}

{% block title %}{{ playlist.name }}{% endblock %}

{% block style %}
  {% load staticfiles %}
  <link href="{% static 'css/playlist.css' %}" rel="stylesheet">

  {% if playlist.is_audio %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/audio.css' %}"/>
  {% else %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/video.css' %}"/>
  {% endif %}
  
{% endblock %}

{% block sidebar %}
  <ul class="nav navbar-nav">
    <li><a href="{% url 'youtubetomp3:playlists' %}">To playlists</a></li>
  </ul>
{% endblock %}

{% block content %}
  {% csrf_token %}

  <div class="card">
    <div class="container">

      <h1 class="in-one-line" id="playlistName">{{ playlist.name }}</h1>

      <a 
        title="Rename playlist"
        class="in-one-line"
        data-toggle="modal"
        href="#changeNameModal"
        onclick="changeName('{% url 'youtubetomp3:change_playlist' playlist.name playlist.name playlist.color %}')">

        <img class="edit-button" src="{% static 'img/edit.png' %}">

      </a>

      <div id="right-buttons" class="in-one-line header-right-button">

        <a id="mediasPopover"
         class="in-one-line" 
         rel="popover" data-original-title="Choose media" data-placement="left" href="#">

          <img id="add" src="{% static 'img/add.png' %}">
          
        </a>

        <a id="colorsPopover"
         class="in-one-line" 
         rel="popover" data-original-title="Pick color" data-placement="left" href="#">

          {% with "img/"|add:playlist.color|add:".png" as image %}
          <img id="color" src="{% static image %}">
          {% endwith %}

        </a>

      </div>

      <hr>

      <table class="songs" border="0">

        {% for media in media_set %}

          {% if playlist.is_audio %}
        
            {% include "youtubetomp3/audio.html" %}

          {% else %}

            {% include "youtubetomp3/video.html" %}

          {% endif %}

        {% endfor %}

      </table>


    </div>
  </div>

  <div id="popover_medias_wrapper" style="display: none">

    {% for media in playlist.get_default_playlist.media_set.all %}

      <div class="chooser-block" style="background-color: #{{ playlist.color }}">
        <a class="chooser-link" id="add_media" href="" 
          onclick="add_to_playlist('{{ playlist.name }}', '{{ media.link_to_play }}')">
            {{ media.name }}
        </a>
      </div>
      
    {% endfor %}

  </div>

  <div id="popover_colors_wrapper" style="display: none">
    <table border="0" style="width: 100%">

      <tr>
          <td>
              <a onclick="changeColor('{% url 'youtubetomp3:change_playlist' playlist.name playlist.name 'fff' %}')"
                 href="#">
                <div class="color-square" style="background-color: #fff"></div>
              </a>
          </td>
          <td>
            <a onclick="changeColor('{% url 'youtubetomp3:change_playlist' playlist.name playlist.name 'ffcccc' %}')"
                 href="#">
              <div class="color-square" style="background-color: #ffcccc"></div>
            </a>
          </td>
          <td>
            <a onclick="changeColor('{% url 'youtubetomp3:change_playlist' playlist.name playlist.name 'cfecfa' %}')"
                 href="#">
              <div class="color-square" style="background-color: #cfecfa"></div>
            </a>
          </td>
      </tr>

      <tr>
          <td>
            <a onclick="changeColor('{% url 'youtubetomp3:change_playlist' playlist.name playlist.name 'ebfde1' %}')"
                 href="#">
              <div class="color-square" style="background-color: #ebfde1"></div>
            </a>
          </td>
          <td>
            <a onclick="changeColor('{% url 'youtubetomp3:change_playlist' playlist.name playlist.name 'f5fec5' %}')"
                 href="#">
              <div class="color-square" style="background-color: #f5fec5"></div>
            </a>
          </td>
          <td>
            <a onclick="changeColor('{% url 'youtubetomp3:change_playlist' playlist.name playlist.name '7b7b7b' %}')"
                 href="#">
              <div class="color-square" style="background-color: #7b7b7b"></div>
            </a>
          </td>
      </tr>

    </table>
  </div>

  <!-- Modal -->
  <div class="modal fade" id="changeNameModal">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title">Change name</h4>
        </div>
        
        <form id="changeNameForm" role="form" method="post" 
              action="{% url 'youtubetomp3:poll_state' %}" 
              enctype="multipart/form-data">

            {% csrf_token %}
            <div class="modal-body">
                <div class="input-group">
                  <input type="text" placeholder="Enter new name here" class="form-control" name="playlist" id="playlist" autofocus>
                </div><!-- /input-group -->
            </div>

            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
              <button type="submit" class="btn btn-success">Change</button>
            </div>
        </form>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal -->

{% endblock %}

{% block javascript %}

  <script src="{% static 'js/jquery.form.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/playlist.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/audio.js' %}"></script>

{% endblock %}

youtubetomp3/templates/youtubetomp3/playlists.html
{% extends "youtubetomp3/base.html" %}

{% block title %}My playlists{% endblock %}

{% block style %}
  {% load staticfiles %}
  <link href="{% static 'css/playlists.css' %}" rel="stylesheet">
{% endblock %}

{% block sidebar %}
  <ul class="nav navbar-nav">
    <li><a href="{% url 'youtubetomp3:index' %}">Home</a></li>
    <li class="active"><a href="{% url 'youtubetomp3:playlists' %}">Playlists</a></li>
  </ul>
{% endblock %}

{% block content %}

  {% if user.username != '' %}  
    <div class="card">
      <div class="container">  
        <h1 class="in-one-line">My Playlists</h1>
         <a title="New playlist" class="in-one-line header-right-button" data-toggle="modal" href="#myModal" type="button">
          <img src="{% static 'img/new-playlist.png' %}">
         </a>
        <hr>

        <div class="row">
          {% for playlist in user.playlist_set.all %}

            <div class="col-xs-6 col-sm-3 col-lg-3">
              <div class="img-thumbnail" style="background-color: #{{ playlist.color }}">
                <a href="{% url 'youtubetomp3:playlist' playlist.name %}" method="GET">

                  {% if playlist.is_audio %}

                    <img class="thumb" src="{% static 'img/audio-playlist-thumb.png' %}">

                  {% else %}
                    
                    <img class="thumb" src="{% static 'img/video-playlist-thumb.png' %}">

                  {% endif %}
                  
                </a>
                <h3>{{ playlist.name }}</h3>
                <a type="button" href="{% url 'youtubetomp3:remove_playlist' playlist.name playlist.is_audio %}" class="close" data-dismiss="modal" aria-hidden="true">&times;</a>
              </div>
            </div>

          {% endfor %}
        </div>
      </div>
    </div>
    
    <!-- Modal -->
    <div class="modal fade" id="myModal">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title">Create playlist</h4>
        </div>
        <form role="form" method="post" action="{% url 'youtubetomp3:new_playlist' %}" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="modal-body">
                <div class="input-group">
                  <input type="text" placeholder="Enter new name here" class="form-control" name="playlist" id="playlist" autofocus>
                  <div class="checkbox">
                    <label>
                      <input type="checkbox" value="is_audio" name="is_audio" id="is_audio" checked> Audio playlist
                    </label>
                  </div>
                </div><!-- /input-group -->
            </div>

            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
              <button type="submit" class="btn btn-success">Create</button>
            </div>
        </form>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->

    {% else %}
      <div class="card">
        <p>
          Please <a href="{% url 'auth_login' %}">login</a> or <a href="{% url 'registration_register' %}">sign up</a>.
        </p>
      </div>
    {% endif %}
    
{% endblock %}


youtubetomp3/templates/youtubetomp3/video.html
{% load staticfiles %}

<tr>

  <td rowspan="2" style="width: 30%; vertical-align: bottom;">

    <video style="margin-bottom: 20px;" width="100%" preload="metadata" controls>
      <source src="{{ media.link_to_play }}" type="video/webm"/>
      <source src="{{ media.link_to_load }}" type="video/mp4"/>
      Bad browser
    </video>

  </td>

  <td style="padding-left: 20px;">

      <p id="name{{ media.id }}" class="in-one-line videoname">{{ media.name }}</p>
      <a
          title="Rename audio"
          data-toggle="modal"
          class="in-one-line"
          href="#changeNameModal"
          onclick="changeMediaName('{% url 'youtubetomp3:change_media' playlist.name media.id %}')">

              <img class="edit-button" src="{% static 'img/edit.png' %}">

      </a>

      <a class="in-one-line" style="float: right;" title="Download" href="{{ media.link_to_load }}"><img src="{% static 'img/download.png' %}"></a>

  </td>


</tr>

<tr>

  <td style="vertical-align: bottom;">

    <div style="margin-bottom: 40px;">
      <a title="Delete" type="button" class="in-one-line close" data-dismiss="modal" aria-hidden="true" 
      href="{% url 'youtubetomp3:remove_media' playlistName=playlist.name media=media.link_to_play %}" 
      method="GET">
                &times;
      </a>
    </div>

  </td>

</tr>